---
- hosts: client-server
  connection: ssh
  become: yes
  vars:
    doc_root: /var/www/html/
  tasks:

  - name: Install httpd and other tools
    yum:
        name: "{{item}}"
        state: present
    with_items:
        - htop
        - elinks
        - ntp
        - php
        - mysql-server
        - mysql



  - name: start httpd amd mysql service
    service:
        name: "{{item}}"
        state: restarted
    with_items:
        - mysqld
  - name: Enabled httpd & mysqldservice
    service:
        name: "{{item}}"
        enabled: yes
    with_items:
        - httpd
        - mysqld

  - name: Index file copying
    copy:
      src: ./index.html
      dest: "{{doc_root}}"
      owner: apache
      group: apache
      mode: 0644
    notify: httpd restarted


  handlers:
  - name: httpd restarted
    service:
        name: httpd
        state: restarted
